Automatically detect packageManager
microsoft/vscode-eslint pull request #1646
Opened 2023-04-28 22:46 UTC by wilkinson4

Deprecate the packageManager setting, and automatically detect it with the vscode command.

2023-04-28 22:46 UTC, wilkinson4 commented
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

2023-04-28 22:48 UTC, wilkinson4 commented
First time making a PR to a language server so please let me know if I missed something.

2023-05-02 07:30 UTC, dbaeumer requested changes
See comment about resolvedGlobalPackageManagerPath

2023-05-02 07:30 UTC, dbaeumer commented on server/src/eslint.ts
> -			settings.resolvedGlobalPackageManagerPath = GlobalPaths.get(settings.packageManager);
This code can't be removed since the property is referenced here: https://github.com/microsoft/vscode-eslint/blob/d8214448aa1ba338c84184239bfee66cea24fbaa/server/src/eslint.ts#L875 and the value is essential for resolving global node modules.

2023-05-05 20:49 UTC, MariaSolOs requested changes

2023-05-05 20:49 UTC, MariaSolOs commented on server/src/paths.ts
> +			if (realpath.toLowerCase() === result.toLowerCase()) {
It seems like your PR made some unintended whitespace changes. I suggest removing them for a cleaner `git` history.

2023-05-05 20:49 UTC, MariaSolOs commented on client/src/client.ts
> +				'npm.packageManager'
You can use the [shared type](https://github.com/microsoft/vscode-eslint/blob/28910c7e2310d7a236198d47b269829066d4fdc7/%24shared/settings.ts#L150) instead of redefining it again here.

2023-05-05 20:49 UTC, MariaSolOs commented on README.md
> -- `eslint.packageManager`: controls the package manager to be used to resolve the ESLint library. This has only an influence if the ESLint library is resolved globally. Valid values are `"npm"` or `"
I don't think we should remove this. Instead we should mention that the setting is now deprecated and why it isn't needed anymore. This matches what we did with `eslint.autoFixOnSave`.

2023-05-05 21:22 UTC, wilkinson4 commented on server/src/paths.ts
> +			if (realpath.toLowerCase() === result.toLowerCase()) {
These changes came from the lint script that I ran with the --fix option. I can undo them if we don't want the changes.

2023-05-05 21:35 UTC, MariaSolOs commented on server/src/paths.ts
> +			if (realpath.toLowerCase() === result.toLowerCase()) {
Oh, in that case yeah we should leave them to make sure the codebase is properly linted. Kind of inconvenient they're not in their original PRs though. Maybe we should have a lint PR check @dbaeumer?

2023-05-05 21:35 UTC, MariaSolOs approved these changes

2023-05-15 22:43 UTC, Skylerspencer commented on server/src/eslint.ts
> -			settings.resolvedGlobalPackageManagerPath = GlobalPaths.get(settings.packageManager);
Thanks

2023-05-18 00:39 UTC, wilkinson4 commented
@dbaeumer anything else that needs to be addressed in this PR?

2023-05-18 08:21 UTC, dbaeumer commented
IMO the change can be breaking for users that had different values set for ESLint and the package manager extension. IMO we should deprecated the value and code wise do the following:

- read ESLint's value AND the value through the command and consider their default values.

If both values are the same pint a message to the channel that the eslint value is deprecated and will be removed in the future. Use either of them

If the values are different print a message to the channel that the value is deprecated and that we will not honor it in the future and that we moved to `npm.packagemanager`. I would still use the eslint value for a while.

Breaking changes usually cause swirl especially since we will receive issue reports for it. This is why I try to avoid this. 

Sorry for detecting this so late.

2023-05-18 15:17 UTC, Skylerspencer commented
> Deprecate the packageManager setting, and automatically detect it with the vscode command.

no

2023-05-18 21:09 UTC, MariaSolOs commented on client/src/client.ts
> +				client.warn('The ESLint setting packageManager is deprecated, and will be removed in the future. Please update your configuration.', {}, true);
I think it would be useful to mention whether the provided manager matches the detected one, so that the user can act accordingly.

E.g.: In here log `"Detected package manager matches the one in the deprecated packageManager setting. This setting will be removed in the future, so you can remove it from your configuration."`, and in line 593 `"Detected package manager differs from the one in the deprecated packageManager setting. We will honor this setting until it is removed."`

2023-05-18 22:31 UTC, MariaSolOs approved these changes

2023-05-19 11:15 UTC, dbaeumer requested changes
See other commants.

2023-05-19 11:15 UTC, dbaeumer commented on client/src/client.ts
> +			client.warn('Detected package manager differs from the one in the deprecated packageManager setting. We will honor this setting until it is removed.', {}, true);
We should include the two values in the message so that the user already knows about them and can make a decision how to prceed.

2023-05-19 11:15 UTC, dbaeumer commented on client/src/client.ts
> +				client.warn('Detected package manager matches the one in the deprecated packageManager setting. This setting will be removed in the future, so you can remove it from your configuration.', {}, tru
I would actually not show a notification in this case (true -> false) since there is no action the user needs to take. Too many notification can be annoying.

2023-05-19 11:15 UTC, dbaeumer commented
@wilkinson4 Forgot to say thanks for working on this.

2023-05-19 14:09 UTC, wilkinson4 commented
> @wilkinson4 Forgot to say thanks for working on this.

No problem!

2023-05-23 20:57 UTC, wilkinson4 commented
> See other commants.


@dbaeumer Following up on this one. Made the recommended changes.

2023-05-24 07:57 UTC, dbaeumer approved these changes

2023-05-24 08:39 UTC, aeschli approved these changes

2023-05-24 08:40 UTC, merged